version: '3'
services:
  nodejs:
    container_name: crawlerJS
    build: ''
    ports:
      - '51220:17994'
    volumes:
      - ../backend/:/app/
    restart: always
    depends_on:
      - crawlerDB
    tty: true
    privileged: true
  
  note_db:
    container_name: crawlerDB
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - 51206:3306
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: harunonaru

  phpmyadmin:
    depends_on:
      - crawlerDB
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '51280:80'
    environment:
      PMA_HOST: crawlerDB
      MYSQL_ROOT_PASSWORD: harunonaru